### ISSUE TITLE
pyx volume empty, override properties not used.

### ISSUE THREAD

**Issue by laundmo** [emcniece/DockerYourXyzzy#12]
there are 2 issues that i feel are connected:

when building with docker-compose, the `.pyx` volume is created but its empty. reading the dockerfile and opening a shell in the container reveals that the volume should contain the contents of the `/project` folder.

at the same time, changes in `overrides/build.properties` have no effect. i tested this with anti spam settigns and blank cards, both have no effect.

`docker-compose logs pyx` result: https://pastebin.com/w7W6gCDa

**Comment by emcniece** [comment]
I wonder if the latest Dockerfile refactor deprecated `overrides/build.properties`. Can you get any overrides to work if you specify them in `CMD` a la https://github.com/emcniece/DockerYourXyzzy#run-with-overrides ?

**Comment by emcniece** [comment]
Yeah, it looks like the overrides directory is added (https://github.com/emcniece/DockerYourXyzzy/blob/master/Dockerfile#L22) but nothing is done with it after the fact.

Perhaps `entrypoint.sh` should append the overrides to the main `build.properties` on startup...

**Comment by laundmo** [comment]
would appending the overrides work? i dont know how the build.properties is read, so im unsure whether duplicate lines would cause issues, but if its as simple as appending, i can figure something out.

**Comment by laundmo** [comment]
it also seems that i was mistaken, the `.pyx` volume is not meant to contain the containers `/project`, its supposed to contain `/output` which is empty in the container, and im unsure what the purpose of that is

**Comment by laundmo** [comment]
changed the `RUN` in the dockerfile to include:
```
 && cp build.properties.example build.properties.a \
 && cat build.properties.a /overrides/build.properties > build.properties \
```
and prepended this to the `CMD`:
```
cat build.properties.a /overrides/build.properties > build.properties && 
```

it seems to work, but i configured it to use postgres as a database, the only issue being that the postgres database is empty, so all the queries fail...

edit: importing the cah_cards.sql seems to have worked, tho it should be noted that the docker compose file, as it is in this repo, is running a postgres container for nothing, since by default sqlite is used and postgres cant just be enabled in the config
