### ISSUE TITLE
"latest, run, x, x-run" does not work on Docker Synology

### ISSUE THREAD

**Issue by legolass73** [emcniece/DockerYourXyzzy#2]
Hello, for 1 week I've been trying to make DockerYourXyzzy work on my Synology nas via Synology docker and it doesn't work.
"latest, run, x, x, x-run" starts but I can't access it by web, I tried putting different port but nothing does it

**Comment by emcniece** [comment]
Hi, thanks for the report. What variant of Linux are you on?

Just pushed some updates to master, including an overhauled Docker image. Check out the new compose file, give `emcniece/dockeryourxyzzy:3` a shot.
